-- Elimina las tablas si ya existen
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMP CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEPT CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Crear tabla DEPT
CREATE TABLE DEPT (
    DEPTNO NUMBER(2,0) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

-- Crear tabla EMP
CREATE TABLE EMP (
    EMPNO NUMBER(4,0) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4,0),
    HIRE_DATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2,0),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);
